# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['app/run.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app/templates/index.html', 'app/templates'),
    ],
    hiddenimports=[
        'docx2python',
        'docx2python.main',
        'docx2python.docx_output',
        'docx2python.iterators',
        'docx2python.docx_reader',
        'docx2python.docx_context',
        'docx2python.docx_text',
        'docx2python.merge_runs',
        'docx2python.bullets_and_numbering',
        'docx2python.numbering_formats',
        'docx2python.text_runs',
        'docx2python.forms',
        'lxml',
        'lxml.etree',
        'pydantic_settings',
        'pydantic',
        'fastapi',
        'uvicorn',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='docx2md',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
